trailingComma: es5
endOfLine: lf
overrides:
  - files: "*.md"
    options:
      proseWrap: preserve
  - files: "*.mjs"
    options:
      tabWidth: 2
  - files: "*.css"
    options:
      tabWidth: 2
