---
name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      deployment-url: ${{ steps.deploy.outputs.deployment-url }}
      pages-deployment-alias-url: ${{ steps.deploy.outputs.pages-deployment-alias-url }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@6bed0761d98439e5a578e2877258200ad565ba87 # stable

      - name: Build site
        run: cargo run --release -- --prod

      - name: Upload output files
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: Output Files
          path: out/*

      - uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4
        id: deploy
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy out --project-name=website

  comment:
    name: Comment
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    needs: [build]
    permissions:
      pull-requests: write

    steps:
      - name: Comment deployment-url
        uses: Chatterino/actions-comment-pull-request@e4a76dd2b0a3c2027c3fd84147a67c22ee4c90fa # main
        with:
          comment-tag: preview
          message: |
            | Status  | ✅ Deploy Successful! |
            | :------------ | :------------ |
            | Preview Url:  |  ${{ needs.build.outputs.deployment-url }} |
            | Branch Preview Url:  | ${{ needs.build.outputs.pages-deployment-alias-url }}  |
